# Source this before running any airflow command for the benchmark.
export BENCH_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." && pwd)"
export AIRFLOW_HOME="$BENCH_ROOT/airflow_home"
export AIRFLOW__DATABASE__SQL_ALCHEMY_CONN="postgresql+psycopg2://airflow:airflow@localhost:5433/airflow"
export AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_SIZE=20
export AIRFLOW__DATABASE__SQL_ALCHEMY_MAX_OVERFLOW=40
export AIRFLOW__CORE__EXECUTOR=LocalExecutor
export AIRFLOW__CORE__LOAD_EXAMPLES=False
export AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
export AIRFLOW__CORE__DAGS_FOLDER="$BENCH_ROOT/bench/dags"
# --- the knobs under test ---
export AIRFLOW__CORE__MAX_MAP_LENGTH=${BENCH_MAX_MAP_LENGTH:-200000}
export AIRFLOW__CORE__PARALLELISM=${BENCH_PARALLELISM:-12}
export AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG=${BENCH_MAX_ACTIVE_TASKS_PER_DAG:-200000}
export AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG=${BENCH_MAX_ACTIVE_RUNS_PER_DAG:-1000}
export AIRFLOW__CORE__DEFAULT_POOL_TASK_SLOT_COUNT=${BENCH_POOL_SLOTS:-200000}
export AIRFLOW__SCHEDULER__MAX_TIS_PER_QUERY=${BENCH_MAX_TIS_PER_QUERY:-512}
export AIRFLOW__SCHEDULER__MAX_DAGRUNS_PER_LOOP_TO_SCHEDULE=${BENCH_MAX_DAGRUNS_PER_LOOP:-200}
export AIRFLOW__SCHEDULER__MAX_DAGRUNS_TO_CREATE_PER_LOOP=200
export AIRFLOW__SCHEDULER__SCHEDULER_IDLE_SLEEP_TIME=0.5
export AIRFLOW__DAG_PROCESSOR__REFRESH_INTERVAL=30
export AIRFLOW__SCHEDULER__PARSING_PROCESSES=1
export AIRFLOW__DAG_PROCESSOR__PARSING_PROCESSES=1
export AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK=False
export AIRFLOW__SCHEDULER__TASK_INSTANCE_HEARTBEAT_TIMEOUT=600
# --- api / auth (local only) ---
export AIRFLOW__API__PORT=8080
export AIRFLOW__API__WORKERS=2
export AIRFLOW__CORE__EXECUTION_API_SERVER_URL="http://localhost:8080/execution/"
export AIRFLOW__CORE__AUTH_MANAGER="airflow.api_fastapi.auth.managers.simple.simple_auth_manager.SimpleAuthManager"
export AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS="admin:admin"
export AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS=True
export AIRFLOW__API_AUTH__JWT_SECRET="bench-local-only-not-secret-0123456789abcdef"
export AIRFLOW__API_AUTH__JWT_EXPIRATION_TIME=86400
export AIRFLOW__LOGGING__LOGGING_LEVEL=${BENCH_LOG_LEVEL:-INFO}
export AIRFLOW__LOGGING__BASE_LOG_FOLDER="$AIRFLOW_HOME/logs"
export AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=120
export NO_PROXY="localhost,127.0.0.1"
export PYTHONUNBUFFERED=1
source "$BENCH_ROOT/.venv/bin/activate"
